# Uncomment this line to define a global platform for your project
# platform :ios, '9.0'

source 'https://github.com/CocoaPods/Specs.git'

target 'OriginStamp-Mac' do
  # Comment this line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for OriginStamp-Mac
  pod 'AFNetworking', '~> 3.0'
  pod 'XCGLogger', '~> 3.3'
  pod 'AppSandboxFileAccess'

  target 'OriginStamp-MacTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'OriginStamp-MacUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
